services:
  - type: web
    name: event-review-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: MONGO_URI
        value: <your-mongo-uri>

  - type: worker
    name: sentiment-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python analyzer.py"
    plan: free
    envVars:
      - key: MONGO_URI
        value: <your-mongo-uri>
